version: "3.9"

services:
  ros-noetic-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: "developer"
        UID: "${HOST_UID-1000}"
        GID: "${HOST_GID-1000}"
    container_name: autorace-noetic-dev
    network_mode: host
    privileged: true
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID-0}
      - ROS_MASTER_URI=${ROS_MASTER_URI-http://localhost:11311}
      - ROS_HOSTNAME=${ROS_HOSTNAME-localhost}
      - TZ=Asia/Seoul
    volumes:
      - ${HOME}/autorace_kkk_ws:/home/developer/autorace_kkk_ws:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/home/developer/.Xauthority:rw
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
    devices:
      - /dev/dri:/dev/dri
    working_dir: /home/developer/autorace_kkk_ws
    stdin_open: true
    tty: true

