wheel_base: 0.26
wheel_radius: 0.034
odom_frame: odom
base_frame: base_link
odom_topic: /wheel_odom
use_imu_heading: true
imu_topic: /imu
rpm_scale: 0.073
servo_center: 0.57165
publish_tf: false          
rate: 30.0
steer_gain: 1.2            # 서보→라디안 보정 게인 (튜닝)